In [49]:
import os
import pandas as pd
import pingouin as pg
import seaborn as sns
import glob
from nltk.tokenize import word_tokenize
import nltk
# Download NLTK data (tokenizers)
nltk.download('punkt')
#pyspellchecker
from spellchecker import SpellChecker

[nltk_data] Downloading package punkt to /Users/Nikita/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [10]:
os.chdir(os.path.join(".."))

In [11]:
os.getcwd()

'/Users/Nikita/Desktop/EPL/experimental_psycholinguistics_2023/Exam_experiment'

### a-responses

In [50]:
json_files = glob.glob(os.path.join("in","a","*.json"))  # Adjust the path to your actual directory
dataframes = [pd.read_json(file) for file in json_files]
a_df = pd.concat(dataframes, ignore_index=True)
a_df

,acc,accuracy,average_response_time,avg_rt,background,canvas_backend,clock_backend,closed,color_backend,count_experiment,...,response_time_practice_intro2,time_practice_intro1,time_practice_intro2,response_experiment_intro,response_time_experiment_intro,time_experiment_intro,PERSISTENT,TEMPORARY,credentialless,originAgentCluster
0,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,11414.0,26.0,35005.0,enter,9848.0,140695.0,NaN,NaN,NaN,NaN
176,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,11414.0,26.0,35005.0,enter,9848.0,140695.0,NaN,NaN,NaN,NaN
177,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,11414.0,26.0,35005.0,enter,9848.0,140695.0,NaN,NaN,NaN,NaN
178,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,11414.0,26.0,35005.0,enter,9848.0,140695.0,NaN,NaN,NaN,NaN
179,undefined,undefined,undefined,undefined,#3d3846,osweb,osweb,False,osweb,0,...,11414.0,26.0,35005.0,enter,9848.0,140695.0,NaN,NaN,NaN,NaN

In [52]:
useful_col = ["sound", "response"]
df_a = a_df[useful_col].copy()
df_a['sound'] = df_a['sound'].astype(str)
df_a

    sound                              response
0      18      mary could not discuss the thing
1      17        the bomb exploded with a blast
2     n-1       the roses bushes quickly thorns
3     n-2   we should have considered the juice
4      10          You are considering the gang
..    ...                                   ...
175    12        nancy should consider the fist
176  n-22        the farmer harvested his crops
177     5  roof poured the water down the drain
178    15            i've spoken about the pile
179  n-20      nancy had considered the sleeves

[180 rows x 2 columns]

In [34]:
correct_df = pd.read_csv(os.path.join("in","sentences_3.csv"), delimiter=";", decimal=",")
correct_df

   predictability                                sentences sound
0             (H)          A rose bush has prickly thorns.   n-1
1             (L)     We should have considered the juice.   n-2
2             (H)  The fruit was shipped in wooden crates.   n-3
3             (L)    Bob could have known about the spoon.   n-4
4             (H)    Ruth poured the water down the drain.   n-5
..            ...                                      ...   ...
59            (L)               Tom will discuss the swan.    28
60            (L)        Ann was interested in the breath.    29
61            (H)          This nozzle sprays a fine mist.    30
62            (L)      Ruth hopes he heard about the hips.    31
63            (L)            Tom is talking about the fee.    32

[64 rows x 3 columns]

In [53]:
merged_df_a = pd.merge(df_a, correct_df, on='sound')
merged_df_a = merged_df_a.sort_values(by='sound', ascending=True)
#df_a_sorted
merged_df_a

,sound,response,predictability,sentences
167,1,A rose soon,(H),A rose bush has prickly thorns.
165,1,a rosebush has pricky thorns,(H),A rose bush has prickly thorns.
169,1,a rosebush have prickley thornes,(H),A rose bush has prickly thorns.
166,1,The rose bushes quickly thorns.,(H),A rose bush has prickly thorns.
168,1,a rosebush has prickly thorns,(H),A rose bush has prickly thorns.
...,...,...,...,...
56,n-32,Thomas is talking about the fee.,(L),Tom is talking about the fee.
57,n-32,Tom is talking about the fee.,(L),Tom is talking about the fee.
59,n-32,tom is talking about the fee,(L),Tom is talking about the fee.
55,n-32,Tom is talking about the fee,(L),Tom is talking about the fee.
58,n-32,Thom is talking about the fee,(L),Tom is talking about the fee.

In [56]:
# Convert "response" and "sentences" columns to lowercase
merged_df_a['response'] = merged_df_a['response'].str.lower()
merged_df_a['sentences'] = merged_df_a['sentences'].str.lower()

# tokenize the words 
merged_df_a['response_words'] = merged_df_a['response'].apply(word_tokenize)
merged_df_a['sentence_words'] = merged_df_a['sentences'].apply(word_tokenize)

# Initialize spell checker
spell = SpellChecker()

# Correct spelling in response words
merged_df_a['response_words'] = merged_df_a['response_words'].apply(lambda words: [spell.correction(word) for word in words])


# Comparing the lists of words and counting the correct ones
merged_df_a['correct_word_count'] = [sum(word in sentence_words for word in response_words)
                                   for response_words, sentence_words
                                   in zip(merged_df_a['response_words'], merged_df_a['sentence_words'])]

print(merged_df_a[['sound', 'response', 'sentences', 'correct_word_count']])

    sound                          response                        sentences  \
167     1              a rose          soon  a rose bush has prickly thorns.
165     1      a rosebush has pricky thorns  a rose bush has prickly thorns.
169     1  a rosebush have prickley thornes  a rose bush has prickly thorns.
166     1   the rose bushes quickly thorns.  a rose bush has prickly thorns.
168     1     a rosebush has prickly thorns  a rose bush has prickly thorns.
..    ...                               ...                              ...
56   n-32  thomas is talking about the fee.    tom is talking about the fee.
57   n-32     tom is talking about the fee.    tom is talking about the fee.
59   n-32      tom is talking about the fee    tom is talking about the fee.
55   n-32      tom is talking about the fee    tom is talking about the fee.
58   n-32     thom is talking about the fee    tom is talking about the fee.

     correct_word_count
167                   2
165                   3
169                   3
166                   3
168                   4
..                  ...
56                    6
57                    7
59                    6
55                    6
58                    5

[180 rows x 4 columns]

In [60]:
# Perform t-test using pingouin
t_test_result = pg.ttest(merged_df_a['correct_word_count_x'][merged_df_a['sound'].str.startswith('n-')],
                         merged_df_a['correct_word_count_x'][~merged_df_a['sound'].str.startswith('n-')],
                         paired=False)

# Display t-test result
print(t_test_result)

KeyError: 'correct_word_count_x'

In [58]:
# Save as csv-file
merged_df_a.to_csv(os.path.join('out','df_a.csv'), index=False)

In [17]:
# hertz average
n_hz_mean = (166.7 +165.2 + 167.3 + 165.9 + 170.5)/5
c_hz_mean = (135.6 +140.9 + 138.7 +131.2 + 137.3)/5
c_hz_mean

136.74